# Generated by Django 5.1.4 on 2025-01-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_rename_user_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
